name: "Reusable :: Unit tests :: App"

on:
  workflow_call:
    inputs:
      base-branch-codecov-artifact-name:
        required: true
        type: string
      working-branch-codecov-artifact-name:
        required: true
        type: string
      app-node-modules-cache-key:
        required: true
        type: string
    outputs:
      codecov_app_unit_percentage:
        description: "Total Percentage coverage"
        value: ${{ jobs.unit_testing.outputs.codecov_output_percentage }}
      codecov_app_unit_diff:
        description: "Percentage difference between head branch"
        value: ${{ jobs.unit_testing.outputs.codecov_output_diff }}

jobs:
  base_branch_coverage_check:
    name: "Run base branch"
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.base_ref }}

      - name: "Setup Node.js"
        uses: actions/setup-node@v1
        with:
          node-version: 17.3

      - name:" Cache Node Modules for ui-app"
        id: cache-node-modules-ui-app
        uses: actions/cache@v2
        with:
          path: node_modules
          key: cache-node-modules-ui-app-${{ hashFiles('yarn.lock') }}

      - name: "Install Node modules for ui-app"
        if: steps.cache-node-modules-ui-app.outputs.cache-hit != 'true'
        run: rm -rf node_modules && yarn install --frozen-lockfile

      - name: "Run unit tests"
        run: yarn test:ci --collectCoverageFrom="./src/**" --coverage

      - name: "Upload code coverage for ref branch"
        uses: actions/upload-artifact@v2
        with:
          name: ${{inputs.base-branch-codecov-artifact-name}}
          path: ./coverage/lcov.info

  unit_testing:
    name: Run work branch
    runs-on: macos-11
    outputs:
      codecov_output_percentage: ${{ steps.code-coverage.outputs.percentage }}
      codecov_output_diff: ${{ steps.code-coverage.outputs.diff }}
    steps:
      - name: "Install Node.js"
        uses: actions/setup-node@v1
        with:
          node-version: 17.3

      - uses: actions/checkout@v2

      - name: "Cache Node modules for ui-app"
        id: cache-node-modules-ui-app
        uses: actions/cache@v2
        with:
          path: node_modules
          key: cache-node-modules-ui-app-${{ hashFiles('yarn.lock') }}

      - name: "Install Node modules for ui-app"
        if: steps.cache-node-modules-ui-app.outputs.cache-hit != 'true'
        run: rm -rf node_modules && yarn install --frozen-lockfile

      - name: "Run unit tests"
        id: run_unit_tests
        run: yarn test:ci

      - name: "Upload unit tests report file"
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: ci-app-unit-tests-results
          path: ./ui-app-unit-tests-results.html

      - name: "Upload code coverage info"
        uses: actions/upload-artifact@v2
        with:
          name: ${{inputs.working-branch-codecov-artifact-name}}
          path: ./coverage/lcov.info
