name: Deploy App and Storybook

on:
  workflow_call:
    inputs:
      app-build-artifact-name:
        required: true
        type: string
      storybook-build-artifact-name:
        required: true
        type: string
    secrets:
      gh_token:
        required: true
      gh_pages_full_branch:
        required: true

jobs:
  clear_build:
    name: Clear existing build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check gh-pages branch existence
        shell: bash
        run: |
          chmod -R 777 ./scripts
          echo "##[set-output name=is_ghp_branch_exists;]$(./scripts/ci/gh-actions-is-branch-exists.sh "$GH_PAGES_FULL_BRANCH")"
        env:
          GH_PAGES_FULL_BRANCH: ${{ secrets.gh_pages_full_branch }}
        id: ghp_branch_existence

      - name: Checkout gh-pages branch
        if: ${{ steps.ghp_branch_existence.outputs.is_ghp_branch_exists == 'true' }}
        uses: actions/checkout@v2
        with:
          ref: ${{ secrets.gh_pages_full_branch }}

      - name: Download artifact
        if: ${{ steps.ghp_branch_existence.outputs.is_ghp_branch_exists == 'true' }}
        uses: actions/download-artifact@v2
        with:
          name: script-files
          path: ./scripts

      - name: Update script file
        if: ${{ steps.ghp_branch_existence.outputs.is_ghp_branch_exists == 'true' }}
        shell: bash
        run: chmod -R 777 ./scripts/ci/gh-actions-branch-name-serialize.sh

      - name: Extract branch folder name
        if: ${{ steps.ghp_branch_existence.outputs.is_ghp_branch_exists == 'true' }}
        shell: bash
        run: |
          if [[ $GITHUB_EVENT_NAME = 'push' ]]
          then
            echo "##[set-output name=folder_name;]$GITHUB_WORKSPACE/$(./scripts/ci/gh-actions-branch-name-serialize.sh "${GITHUB_REF#refs/heads/}")"
          elif [[ $GITHUB_EVENT_NAME = 'pull_request' ]]
          then
            echo "##[set-output name=folder_name;]$GITHUB_WORKSPACE/$(./scripts/ci/gh-actions-branch-name-serialize.sh "$GITHUB_BASE_REF")"
          else
            echo "##[set-output name=folder_name;]$GITHUB_WORKSPACE/$(./scripts/ci/gh-actions-branch-name-serialize.sh "${GITHUB_REF#refs/heads/}")"
          fi
        id: branch_folder_name

      - name: Remove Existing build (app and storybook)
        uses: JesseTG/rm@v1.0.2
        if: ${{ success() && steps.ghp_branch_existence.outputs.is_ghp_branch_exists == 'true' }}
        with:
          path: ${{ steps.branch_folder_name.outputs.folder_name }}

      - name: Remove redundant files from the current branch
        if: ${{ steps.ghp_branch_existence.outputs.is_ghp_branch_exists == 'true' }}
        shell: bash
        run: rm -r ./scripts

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        if: steps.auto-commit-action.outputs.changes_detected == 'true' && steps.ghp_branch_existence.outputs.is_ghp_branch_exists == 'true'
        with:
          branch: ${{ secrets.gh_pages_full_branch }}

  deploy:
    name: Deploy new builds
    if: ${{ always() }}
    needs: clear_build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Download artifact - Storybook (build files)
        uses: actions/download-artifact@v2
        with:
          name: ${{ inputs.storybook-build-artifact-name }}
          path: ./sb-build-files

      - name: Download artifact - App (build files)
        uses: actions/download-artifact@v2
        with:
          name: ${{ inputs.app-build-artifact-name }}
          path: ./app-build-files

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: script-files
          path: ./scripts

      - name: Extract branch folder name
        shell: bash
        run: |
          if [[ $GITHUB_EVENT_NAME = 'push' ]]
          then
            echo "##[set-output name=branch;]$(./scripts/ci/gh-actions-branch-name-serialize.sh "${GITHUB_REF#refs/heads/}")"
          elif [[ $GITHUB_EVENT_NAME = 'pull_request' ]]
          then
            echo "##[set-output name=branch;]$(./scripts/ci/gh-actions-branch-name-serialize.sh "$GITHUB_BASE_REF")"
          else
            echo "##[set-output name=branch;]$(./scripts/ci/gh-actions-branch-name-serialize.sh "${GITHUB_REF#refs/heads/}")"
          fi
        id: extract_branch

      - name: Deploy Storybook to GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.gh_token }}
          publish_branch: ${{ secrets.gh_pages_full_branch }}
          publish_dir: ./sb-build-files
          destination_dir: ${{ format('{0}/{1}', steps.extract_branch.outputs.branch, 'storybook') }}

      - name: Deploy App to GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.gh_token }}
          publish_branch: ${{ secrets.gh_pages_full_branch }}
          publish_dir: ./app-build-files
          destination_dir: ${{ format('{0}/{1}', steps.extract_branch.outputs.branch, 'app') }}
