name: Build & Deploy UI app & Storybook
on:
  push:
    branches:
      - develop
      - 'fix/**'
      - 'feat/**'
  pull_request:
    branches:
      - 'fix/**'
      - 'feat/**'

# GH_PAGES_FULL_BRANCH - app-builds-gh-pages

jobs:
  build:
    name: Build UI app and Storybook
    runs-on: macos-latest
    steps:

      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Cache Node Modules
        id: cache-node-modules-ui-app-v1
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-ui-app-v2-${{ hashFiles('yarn.lock') }}

      - name: Install NPM packages
        if: steps.cache-node-modules-ui-app-v1.outputs.cache-hit != 'true'
        run: |
          rm -rf node_modules && yarn install --frozen-lockfile

      - name: Update browserslist
        run: npx browserslist@latest --update-db

      - name: Build App and Storybook
        run: |
          yarn run build:deployment
          yarn run build-storybook -- -o sb-build-files
        env:
          CI: false

      - name: Upload script files
        uses: actions/upload-artifact@v2
        with:
          name: script-files
          path: ./scripts

      - name: Upload production-ready SB build files
        uses: actions/upload-artifact@v2
        with:
          name: sb-build-files
          path: ./sb-build-files

      - name: Upload production-ready App build files
        uses: actions/upload-artifact@v2
        with:
          name: app-build-files
          path: ./build

  clear_build:
    name: Clear existing build
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check gh-pages branch existence
        shell: bash
        run: |
          chmod -R 777 ./scripts
          echo "##[set-output name=is_ghp_branch_exists;]$(./scripts/gh-actions-is-branch-exists.sh "$GH_PAGES_FULL_BRANCH")"
        env:
          GH_PAGES_FULL_BRANCH: ${{ secrets.GH_PAGES_FULL_BRANCH }}
        id: ghp_branch_existence

      - name: Checkout gh-pages branch
        if: ${{ steps.ghp_branch_existence.outputs.is_ghp_branch_exists == 'true' }}
        uses: actions/checkout@v2
        with:
          ref: ${{ secrets.GH_PAGES_FULL_BRANCH }}

      - name: Download artifact
        if: ${{ steps.ghp_branch_existence.outputs.is_ghp_branch_exists == 'true' }}
        uses: actions/download-artifact@v2
        with:
          name: script-files
          path: ./scripts

      - name: Update script file
        if: ${{ steps.ghp_branch_existence.outputs.is_ghp_branch_exists == 'true' }}
        shell: bash
        run: chmod -R 777 ./scripts/gh-actions-branch-name-serialize.sh

      - name: Extract branch folder name
        if: ${{ steps.ghp_branch_existence.outputs.is_ghp_branch_exists == 'true' }}
        shell: bash
        run: |
          if [[ $GITHUB_EVENT_NAME = 'push' ]]
          then
            echo "##[set-output name=folder_name;]$GITHUB_WORKSPACE/$(./scripts/gh-actions-branch-name-serialize.sh "${GITHUB_REF#refs/heads/}")"
          elif [[ $GITHUB_EVENT_NAME = 'pull_request' ]]
          then
            echo "##[set-output name=folder_name;]$GITHUB_WORKSPACE/$(./scripts/gh-actions-branch-name-serialize.sh "$GITHUB_BASE_REF")"
          else
            echo "##[set-output name=folder_name;]$GITHUB_WORKSPACE/$(./scripts/gh-actions-branch-name-serialize.sh "${GITHUB_REF#refs/heads/}")"
          fi
        id: branch_folder_name

      - name: Remove Existing build (app and storybook)
        uses: JesseTG/rm@v1.0.2
        if: ${{ success() && steps.ghp_branch_existence.outputs.is_ghp_branch_exists == 'true' }}
        with:
          path: ${{ steps.branch_folder_name.outputs.folder_name }}

      - name: Remove redundant files from the current branch
        if: ${{ steps.ghp_branch_existence.outputs.is_ghp_branch_exists == 'true' }}
        shell: bash
        run: rm -r ./scripts

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        if: steps.auto-commit-action.outputs.changes_detected == 'true' && steps.ghp_branch_existence.outputs.is_ghp_branch_exists == 'true'
        with:
          branch: ${{ secrets.GH_PAGES_FULL_BRANCH }}

  deploy:
    name: Deploy new builds
    if: ${{ always() && needs.build.result=='success' }}
    needs: [build, clear_build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Download artifact - Storybook (build files)
        uses: actions/download-artifact@v2
        with:
          name: sb-build-files
          path: ./sb-build-files

      - name: Download artifact - App (build files)
        uses: actions/download-artifact@v2
        with:
          name: app-build-files
          path: ./app-build-files

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: script-files
          path: ./scripts

      - name: Extract branch folder name
        shell: bash
        run: |
          if [[ $GITHUB_EVENT_NAME = 'push' ]]
          then
            echo "##[set-output name=branch;]$(./scripts/gh-actions-branch-name-serialize.sh "${GITHUB_REF#refs/heads/}")"
          elif [[ $GITHUB_EVENT_NAME = 'pull_request' ]]
          then
            echo "##[set-output name=branch;]$(./scripts/gh-actions-branch-name-serialize.sh "$GITHUB_BASE_REF")"
          else
            echo "##[set-output name=branch;]$(./scripts/gh-actions-branch-name-serialize.sh "${GITHUB_REF#refs/heads/}")"
          fi
        id: extract_branch

      - name: Deploy Storybook to GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_branch: ${{ secrets.GH_PAGES_FULL_BRANCH }}
          publish_dir: ./sb-build-files
          destination_dir: ${{ format('{0}/{1}', steps.extract_branch.outputs.branch, 'storybook') }}

      - name: Deploy App to GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_branch: ${{ secrets.GH_PAGES_FULL_BRANCH }}
          publish_dir: ./app-build-files
          destination_dir: ${{ format('{0}/{1}', steps.extract_branch.outputs.branch, 'app') }}